# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Set of modules to manage Sale Order imports through a JSON API
repo_name: sale-import
repo_slug: sale-import
travis_apt_packages: []
travis_apt_sources: []
